# Generated by Django 4.2.7 on 2026-02-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_bill_lab_fee_bill_medicine_fee_bill_other_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('pending', 'Pending'), ('paid', 'Paid'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
