# Generated by Django 6.0.2 on 2026-04-11 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_delete_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ui_rating', models.PositiveSmallIntegerField(verbose_name='Overall UI Rating (1-5)')),
                ('registration_easy', models.BooleanField(verbose_name='Was registration easy?')),
                ('navigation_rating', models.PositiveSmallIntegerField(verbose_name='Navigation Ease (1-5)')),
                ('performance_rating', models.PositiveSmallIntegerField(verbose_name='Speed/Performance (1-5)')),
                ('google_login_useful', models.BooleanField(verbose_name='Google Login Useful?')),
                ('appointment_satisfaction', models.PositiveSmallIntegerField(verbose_name='Appointment Booking (1-5)')),
                ('prescription_system_rating', models.PositiveSmallIntegerField(verbose_name='Prescription System Ease (1-5)')),
                ('prescription_clarity', models.PositiveSmallIntegerField(verbose_name='Prescription Clarity (1-5)')),
                ('billing_helpfulness', models.PositiveSmallIntegerField(verbose_name='Billing/Payment Helpfulness (1-5)')),
                ('medical_records_rating', models.PositiveSmallIntegerField(verbose_name='Medical Records Access (1-5)')),
                ('notification_rating', models.PositiveSmallIntegerField(verbose_name='Notification System (1-5)')),
                ('dashboard_organization', models.PositiveSmallIntegerField(verbose_name='Dashboard Organization (1-5)')),
                ('professionalism_rating', models.PositiveSmallIntegerField(verbose_name='System Professionalism (1-5)')),
                ('password_reset_rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Password Reset Ease (1-5)')),
                ('back_button_rating', models.PositiveSmallIntegerField(verbose_name='Back Button Usefulness (1-5)')),
                ('mobile_responsive_rating', models.PositiveSmallIntegerField(verbose_name='Mobile Responsiveness (1-5)')),
                ('experienced_bugs', models.BooleanField(verbose_name='Experienced any bugs?')),
                ('recommendation_likelihood', models.PositiveSmallIntegerField(verbose_name='Recommendation Likelihood (1-5)')),
                ('favorite_feature', models.TextField(verbose_name='Favorite Feature')),
                ('suggestions', models.TextField(verbose_name='Suggestions for Improvement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Feedback',
                'verbose_name_plural': 'System Feedbacks',
                'db_table': 'system_feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
