"""
Django settings for SmartCareSystem project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env if it exists
env_path = BASE_DIR / '.env'
if env_path.exists():
    with open(env_path) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#') and '=' in line:
                key, value = line.split('=', 1)
                # Strip spaces and quotes
                value = value.strip().strip('"').strip("'")
                os.environ[key] = value


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zr(s)mh4z3xq)-k1ufbdo4m0caeo3!-s0azmu39am0wou7ba@e'

# SECURITY WARNING: don't run with debug turned on in production!
IS_RENDER = bool(os.getenv('RENDER'))
DEBUG = os.getenv('DEBUG', 'False' if IS_RENDER else 'True').lower() in ('true', '1', 'yes')

_default_allowed_hosts = (
    'localhost,127.0.0.1,[::1],testserver,'
    'smartcare-system.onrender.com,smartcare-syatem.onrender.com,.onrender.com'
)
ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('DJANGO_ALLOWED_HOSTS', _default_allowed_hosts).split(',')
    if host.strip()
]

# CSRF trusted origins (Render + local)
CSRF_TRUSTED_ORIGINS = [
    "https://smartcare-system.onrender.com",
    "https://smartcare-syatem.onrender.com",
    "https://*.onrender.com",
    "http://127.0.0.1:8000",
    "http://localhost:8000",
]

# Security settings for production
if IS_RENDER:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    # If the site is accessed via HTTPS, ensure CSRF cookie is secure
    CSRF_COOKIE_HTTPONLY = True

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Custom apps
    'accounts',
    'appointments',
    'prescriptions',
    'billing',
    'medical_records',
    'core',
    'notifications',

    # Allauth
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'SmartCareSystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notifications.context_processors.notification_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'SmartCareSystem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# If running on Render, use the internal PostgreSQL database
# Note: Host 'dpg-d7bjtevkijhs73aoend0-a' is internal to Render and only works there.
if os.environ.get('RENDER'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'smartcare_db_qd07',
            'USER': 'admin',
            'PASSWORD': 'eLkqUhNkVO24vmlbIcqgtI4qH1MHYuCM',
            'HOST': 'dpg-d7bjtevkijhs73aoend0-a',
            'PORT': '5432',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# CSRF failure view
CSRF_FAILURE_VIEW = 'accounts.views.csrf_failure_view'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Custom Authentication Backend
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'accounts.authentication.EmailBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

# Allauth settings
ACCOUNT_ADAPTER = 'allauth.account.adapter.DefaultAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'accounts.adapters.SmartCareSocialAccountAdapter'
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email', 'first_name', 'last_name']
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'
ACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_AUTO_SIGNUP = True
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '').strip()
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET', '').strip()

# Site URL for payment gateways and other services
SITE_URL = os.getenv('SITE_URL', 'http://127.0.0.1:8000')

# Payment Gateway Settings
ESEWA_MERCHANT_CODE = os.getenv('ESEWA_MERCHANT_CODE', 'EPAYTEST')
ESEWA_SUCCESS_URL = f"{SITE_URL}/billing/esewa/success/"
ESEWA_FAILURE_URL = f"{SITE_URL}/billing/esewa/failure/"

KHALTI_SECRET_KEY = os.getenv('KHALTI_SECRET_KEY', 'test_key')
KHALTI_RETURN_URL = f"{SITE_URL}/billing/khalti/callback/"

# Use modern plural APPS for allauth 65+
# This prevents DoesNotExist and MultipleObjectsReturned errors
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'OAUTH_PKCE_ENABLED': True,
        'APPS': [
            {
                'client_id': GOOGLE_CLIENT_ID,
                'secret': GOOGLE_CLIENT_SECRET,
                'key': '',
                'name': 'Google',
                'sites': [1],
                'settings': {
                    'scope': ['profile', 'email'],
                    'auth_params': {'access_type': 'online'},
                }
            }
        ] if GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET else []
    }
}

# Extra CSRF origins from environment
extra_csrf_origins = os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', '')
if extra_csrf_origins.strip():
    CSRF_TRUSTED_ORIGINS.extend(
        origin.strip()
        for origin in extra_csrf_origins.split(',')
        if origin.strip()
    )

# Email settings for password reset and notifications
# Default: console backend (no real delivery). Set EMAIL_BACKEND + credentials in .env for SMTP.
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = (os.getenv('EMAIL_HOST', 'smtp.gmail.com') or 'smtp.gmail.com').strip()
# Port 465 uses implicit SSL; 587 uses STARTTLS (Gmail supports both)
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False') == 'True'
_default_port = '465' if EMAIL_USE_SSL else '587'
EMAIL_PORT = int(os.getenv('EMAIL_PORT', _default_port))
if EMAIL_USE_SSL:
    EMAIL_USE_TLS = False
else:
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = (os.getenv('EMAIL_HOST_USER', '') or '').strip()
# Gmail App Passwords are 16 characters; Google often displays them with spaces—remove them
_raw_pw = (os.getenv('EMAIL_HOST_PASSWORD', '') or '').strip()
EMAIL_HOST_PASSWORD = _raw_pw.replace(' ', '')
# If DEFAULT_FROM_EMAIL is unset, prefer the SMTP user so Gmail accepts the From address
_default_from = (os.getenv('DEFAULT_FROM_EMAIL', '') or '').strip()
DEFAULT_FROM_EMAIL = _default_from or EMAIL_HOST_USER or 'noreply@localhost'

# Optional: Resend (https://resend.com) — avoids Gmail SMTP/App Password issues. Set RESEND_API_KEY in .env.
RESEND_API_KEY = (os.getenv('RESEND_API_KEY', '') or '').strip()
RESEND_FROM_EMAIL = (os.getenv('RESEND_FROM_EMAIL', '') or '').strip() or 'onboarding@resend.dev'

# When DEBUG is True and sending fails, show OTP on the next page (local dev only; never in production).
EMAIL_DEV_OTP_FALLBACK = os.getenv('EMAIL_DEV_OTP_FALLBACK', 'true').lower() in ('true', '1', 'yes')
