# Generated by Django 6.0.4 on 2026-04-09 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='allergies',
        ),
    ]
