# Generated by Django 6.0.2 on 2026-03-24 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_appointment_address_appointment_age_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Health Metric',
                'verbose_name_plural': 'Health Metrics',
                'db_table': 'health_metrics',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalChartTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metrics', models.ManyToManyField(related_name='chart_templates', to='charts.healthmetric')),
            ],
            options={
                'verbose_name': 'Medical Chart Template',
                'verbose_name_plural': 'Medical Chart Templates',
                'db_table': 'medical_chart_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VideoCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('waiting', 'Waiting'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('missed', 'Missed')], default='scheduled', max_length=20)),
                ('room_id', models.CharField(max_length=100, unique=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recording_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_call', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_calls', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video Call',
                'verbose_name_plural': 'Video Calls',
                'db_table': 'video_calls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientHealthChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.healthmetric')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_charts', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_charts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Health Chart',
                'verbose_name_plural': 'Patient Health Charts',
                'db_table': 'patient_health_charts',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['patient', 'metric', 'recorded_at'], name='patient_hea_patient_27f48b_idx')],
            },
        ),
    ]
