# Generated by Django 6.0.2 on 2026-03-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_alter_prescription_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='consultation_type',
            field=models.CharField(choices=[('physical_visit', 'Physical Visit'), ('online_consultant', 'Online Consultant')], default='physical_visit', max_length=20),
        ),
    ]
