# Generated by Django 6.0.2 on 2026-04-11 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responses', models.JSONField(help_text='Question number (1–20) as string keys mapped to scores 1–5.')),
                ('additional_comments', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Survey submission',
                'verbose_name_plural': 'Survey submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
