# Generated by Django 6.0.2 on 2026-04-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveysubmission',
            name='responses',
            field=models.JSONField(help_text='Question number (1–19) as string keys mapped to scores 1–5.'),
        ),
    ]
