# Generated by Django 4.2.7 on 2026-02-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='allergies',
            field=models.TextField(blank=True, help_text='List any allergies', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(blank=True, choices=[('consultation', 'General Consultation'), ('followup', 'Follow-up Visit'), ('emergency', 'Emergency'), ('checkup', 'Routine Check-up'), ('specialist', 'Specialist Consultation'), ('vaccination', 'Vaccination')], default='consultation', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='current_medications',
            field=models.TextField(blank=True, help_text='Current medications', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='emergency_relationship',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Previous medical conditions', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('insurance', 'Insurance'), ('online', 'Online Payment')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='policy_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='previous_visits',
            field=models.CharField(blank=True, choices=[('first_time', 'First Time Visit'), ('returning', 'Returning Patient'), ('followup', 'Follow-up Visit')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low - Routine check-up'), ('medium', 'Medium - Non-urgent medical issue'), ('high', 'High - Urgent but not emergency'), ('critical', 'Critical - Emergency')], default='medium', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
