# Generated by Django 6.0.2 on 2026-03-21 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('appointment_booked', 'Appointment Booked'), ('appointment_confirmed', 'Appointment Confirmed'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_completed', 'Appointment Completed'), ('bill_paid', 'Bill Paid'), ('bill_generated', 'Bill Generated'), ('prescription_created', 'Prescription Created'), ('medical_record_created', 'Medical Record Created'), ('lab_report_uploaded', 'Lab Report Uploaded'), ('doctor_assigned', 'Doctor Assigned'), ('payment_reminder', 'Payment Reminder'), ('appointment_reminder', 'Appointment Reminder'), ('system_update', 'System Update'), ('user_registered', 'New User Registered'), ('profile_updated', 'Profile Updated')], max_length=50, unique=True)),
                ('email_subject', models.CharField(max_length=200)),
                ('email_body', models.TextField()),
                ('sms_message', models.CharField(max_length=160)),
                ('push_title', models.CharField(max_length=100)),
                ('push_body', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['notification_type'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_appointments', models.BooleanField(default=True)),
                ('email_bills', models.BooleanField(default=True)),
                ('email_prescriptions', models.BooleanField(default=True)),
                ('email_medical_records', models.BooleanField(default=True)),
                ('email_system_updates', models.BooleanField(default=True)),
                ('sms_appointments', models.BooleanField(default=False)),
                ('sms_bills', models.BooleanField(default=True)),
                ('sms_urgent', models.BooleanField(default=True)),
                ('push_appointments', models.BooleanField(default=True)),
                ('push_bills', models.BooleanField(default=True)),
                ('push_prescriptions', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('appointment_booked', 'Appointment Booked'), ('appointment_confirmed', 'Appointment Confirmed'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_completed', 'Appointment Completed'), ('bill_paid', 'Bill Paid'), ('bill_generated', 'Bill Generated'), ('prescription_created', 'Prescription Created'), ('medical_record_created', 'Medical Record Created'), ('lab_report_uploaded', 'Lab Report Uploaded'), ('doctor_assigned', 'Doctor Assigned'), ('payment_reminder', 'Payment Reminder'), ('appointment_reminder', 'Appointment Reminder'), ('system_update', 'System Update'), ('user_registered', 'New User Registered'), ('profile_updated', 'Profile Updated')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('is_email_sent', models.BooleanField(default=False)),
                ('is_sms_sent', models.BooleanField(default=False)),
                ('appointment_id', models.PositiveIntegerField(blank=True, null=True)),
                ('bill_id', models.PositiveIntegerField(blank=True, null=True)),
                ('prescription_id', models.PositiveIntegerField(blank=True, null=True)),
                ('medical_record_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('action_text', models.CharField(blank=True, max_length=50)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'), models.Index(fields=['priority'], name='notificatio_priorit_bf8ea0_idx')],
            },
        ),
    ]
